### ISSUE TITLE
Image files missing

### ISSUE THREAD

**Issue by lpwm** [lionrock/HTML5-Example#2]
While running wechat-divination, here comes /img/qiantong.png and /img/animation.png missing problem. Maybe you just forgot to upload these files?

**Comment by forrest-lee** [comment]
Thanks, these files are already exist but names are wrong.
I've fixed the issue in https://github.com/lionrock/H5-Promotion/commit/d16778a5b360e15252c1e91d59bb4c3e19a9ae89 now. Sorry about that.
